// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/dulev/ganki/server/controllers"
	"github.com/dulev/ganki/server/controllers/middleware"
	"github.com/dulev/ganki/server/user"
)

import (
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

// Injectors from wire.go:

func InitializeServer() *GankiServer {
	db := NewDatabase()
	sessionManager := middleware.NewSessionManager(db)
	userService := user.NewUserService(db)
	userController := controllers.NewUserController(db, sessionManager, userService)
	gankiServer := NewGankiServer(db, userController)
	return gankiServer
}
